services:
  backend-antiginx:
    image: ghcr.io/prawo-i-piesc/backend-antiginx:latest
    container_name: backend-antiginx
    restart: unless-stopped

    ports:
      - "${BACKEND_PORT}:4000"

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - COOKIE_SECURE=${COOKIE_SECURE:-true}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL:-}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-}

    networks:
      - vpn-net

networks:
  vpn-net:
    external: true